import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";
import type { TechnicianJobHistoryItem, TechnicianJobListItem, TechnicianJobListQuery, TechnicianPaginationMeta } from "@/domain/technician-jobs/contracts";
import { TechnicianJobError } from "@/domain/technician-jobs/errors";
import { createAuthorizedDataContext } from "@/lib/supabase/privileged-server";

const JOB_SELECT = `id,order_no,status,problem_description,service_type,quoted_price,admin_notes,scheduled_at,created_at,updated_at,customer:customers!orders_customer_id_fkey(name,phone,address),branch:branches!orders_branch_id_fkey(id,code,name)`;
type DataRecord = Record<string, unknown>;
function meta(page:number,pageSize:number,total:number):TechnicianPaginationMeta{const totalPages=Math.max(1,Math.ceil(total/pageSize));return{page,pageSize,total,totalPages,hasMore:page<totalPages};}
function fail(cause?:unknown):never{throw new TechnicianJobError("TECHNICIAN_JOB_DATA_ACCESS_FAILED","Job data is temporarily unavailable. Please try again.",503,cause instanceof Error?{cause}:undefined);}
function record(value:unknown):DataRecord{if(!value||typeof value!=="object"||Array.isArray(value))fail();return value as DataRecord;}
function relation(value:unknown):DataRecord{return record(Array.isArray(value)?value[0]:value);}
function text(value:unknown){return typeof value==="string"?value:String(value??"");}
function nullableText(value:unknown):string|null{return value===null||value===undefined?null:text(value);}
function addressSummary(value:string){return value.length<=90?value:`${value.slice(0,87)}...`;}
async function technicianContext():Promise<{supabase:SupabaseClient;technicianId:string}>{const context=await createAuthorizedDataContext("job:view_assigned");if(context.identity.role!=="TECHNICIAN")throw new TechnicianJobError("TECHNICIAN_JOB_PERMISSION_DENIED","An active Technician session is required.",403);const{data,error}=await context.supabase.from("technicians").select("id,profile:profiles!technicians_profile_id_fkey(active,role)").eq("profile_id",context.identity.profileId).eq("active",true).maybeSingle();if(error)fail(error);if(!data)throw new TechnicianJobError("TECHNICIAN_JOB_PERMISSION_DENIED","The Technician profile is inactive or unavailable.",403);const profile=relation(data.profile);if(profile.active!==true||profile.role!=="TECHNICIAN")throw new TechnicianJobError("TECHNICIAN_JOB_PERMISSION_DENIED","The Technician profile is inactive or unavailable.",403);return{supabase:context.supabase,technicianId:data.id};}
function baseJob(value:unknown){const row=record(value);const customer=relation(row.customer);const branch=relation(row.branch);const address=text(customer.address);return{id:text(row.id),orderNo:text(row.order_no),status:text(row.status),customerName:text(customer.name),addressSummary:addressSummary(address),branch:{id:text(branch.id),code:text(branch.code),name:text(branch.name)},serviceType:text(row.service_type),quotedPrice:Number(row.quoted_price),scheduledAt:nullableText(row.scheduled_at),createdAt:text(row.created_at),updatedAt:text(row.updated_at)};}
export async function listTechnicianJobsPaged(query:TechnicianJobListQuery){const{supabase,technicianId}=await technicianContext();const start=(query.page-1)*query.pageSize;const end=start+query.pageSize-1;if(query.scope==="history"){const{data,count,error}=await supabase.from("orders").select(JOB_SELECT,{count:"exact"}).eq("assigned_technician_id",technicianId).in("status",["JOB_DONE","REVIEWED","CLOSED"]).order("updated_at",{ascending:false}).order("id",{ascending:false}).range(start,end);if(error)fail(error);const jobs:TechnicianJobHistoryItem[]=(data??[]).map((value)=>{const job=baseJob(value);return{id:job.id,orderNo:job.orderNo,status:job.status as TechnicianJobHistoryItem["status"],customerName:job.customerName,addressSummary:job.addressSummary,branch:job.branch,serviceType:job.serviceType,quotedPrice:job.quotedPrice,scheduledAt:job.scheduledAt,createdAt:job.createdAt,updatedAt:job.updatedAt};});return{jobs,pagination:meta(query.page,query.pageSize,count??0)};}const{data,count,error}=await supabase.from("orders").select(JOB_SELECT,{count:"exact"}).eq("assigned_technician_id",technicianId).in("status",["ASSIGNED","IN_PROGRESS"]).order("status",{ascending:false}).order("scheduled_at",{ascending:true,nullsFirst:false}).order("created_at",{ascending:true}).order("id",{ascending:true}).range(start,end);if(error)fail(error);const jobs:TechnicianJobListItem[]=(data??[]).map((value)=>{const job=baseJob(value);return{id:job.id,orderNo:job.orderNo,status:job.status as TechnicianJobListItem["status"],customerName:job.customerName,addressSummary:job.addressSummary,branch:job.branch,serviceType:job.serviceType,quotedPrice:job.quotedPrice,scheduledAt:job.scheduledAt,createdAt:job.createdAt};});return{jobs,pagination:meta(query.page,query.pageSize,count??0)};}
