project_id = "sejukops-assessment"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[storage]
enabled = true
file_size_limit = "75MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://localhost:3000/**"]
