import json, pathlib, html, re, struct
root=pathlib.Path(__file__).resolve().parents[3] / 'reports/ui-mock-gallery'
evidence=json.loads((root/'browser-results.json').read_text())
latest={}
for shot in evidence['screenshots']:
 if not shot['title'].startswith('未完成：'):
  latest[re.sub(r'^\d+-','',shot['file'])]=shot
shots=list(latest.values())
groups=['入口與帳號','Dashboard','工單與排程','AI Assist 與 AI Workspace','知識庫','AI 平台設定','員工與 Owner 預覽','Demo 管理與診斷','更多功能狀態','空白、錯誤與額度狀態']
shots.sort(key=lambda s:(groups.index(s['group']) if s['group'] in groups else 100,int(s['file'].split('-')[0])))
for shot in shots:
 data=(root/shot['file']).read_bytes()
 assert data[:8]==b'\x89PNG\r\n\x1a\n'
 assert struct.unpack('>II',data[16:24])==(1920,1080),shot['file']
# Keep earlier evidence on disk in /tmp; only reviewed current screens ship.
keep={s['file'] for s in shots}
for file in root.glob('*.png'):
 if file.name not in keep:file.unlink()
evidence['screenshots']=shots
evidence['uniqueScreenshots']=len(shots)
(root/'browser-results.json').write_text(json.dumps(evidence,ensure_ascii=False,indent=2))
cards=[]
for i,s in enumerate(shots):
 cards.append(f'''<article class="card" data-group="{html.escape(s['group'])}" data-search="{html.escape(s['title']+' '+s['persona']+' '+s['scenario'])}"><button class="image-button" data-index="{i}" aria-label="放大：{html.escape(s['title'])}"><img src="{s['file']}" loading="lazy" width="1920" height="1080" alt="{html.escape(s['title'])}"></button><div class="caption"><span class="tag">{html.escape(s['group'])}</span><h2>{html.escape(s['title'])}</h2><p>{html.escape(s['persona'])} · {html.escape(s['scenario'])}</p><a href="{s['file']}" download>下載原圖 ↗</a></div></article>''')
buttons=''.join(f'<button data-filter="{html.escape(g)}">{html.escape(g)}</button>' for g in groups if any(s['group']==g for s in shots))
page='''<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SejukOps · 16:9 UI 圖庫</title><style>
:root{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#173e36;background:#f3f6f5}*{box-sizing:border-box}body{margin:0}header{padding:40px max(24px,5vw) 26px;background:linear-gradient(120deg,#092635,#155951);color:#fff}header .eyebrow{font-size:12px;letter-spacing:2px;color:#a7d7c7}h1{font-size:clamp(28px,4vw,46px);margin:10px 0}header p{max-width:980px;line-height:1.8;color:#d2e7e0}header .metrics{display:flex;gap:12px;flex-wrap:wrap}.metrics span{padding:8px 13px;background:#ffffff12;border:1px solid #ffffff22;border-radius:6px;font-size:13px}.toolbar{position:sticky;top:0;z-index:2;padding:16px max(24px,5vw);background:#fffffff2;backdrop-filter:blur(8px);border-bottom:1px solid #d9e5df}.filters{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.filters button{background:#f3f6f5;color:#355d52;border:1px solid #dbe6e0;padding:8px 11px;border-radius:20px;cursor:pointer}.filters button.active{background:#166c62;border-color:#166c62;color:#fff}input{width:min(440px,100%);padding:12px 14px;border:1px solid #cedbd4;border-radius:8px;font:inherit}.count{font-size:13px;color:#667e74;margin-left:12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;padding:28px max(24px,5vw) 60px}.card{border:1px solid #dce7e0;background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 18px #0a31260a}.image-button{display:block;width:100%;padding:0;border:0;cursor:zoom-in;background:#e8eeeb}.card img{display:block;width:100%;height:auto;aspect-ratio:16/9;object-fit:contain}.caption{padding:18px 20px}.tag{font-size:11px;color:#397d69;letter-spacing:.5px}.caption h2{font-size:18px;margin:7px 0}.caption p{color:#758c81;font-size:12px}.caption a{font-size:13px;color:#166c62}footer{padding:20px max(24px,5vw);font-size:13px;line-height:1.8;color:#738379}dialog{width:96vw;max-width:1800px;border:0;background:#071923;color:#fff;padding:14px;border-radius:12px}dialog::backdrop{background:#071923dd}dialog img{width:100%;max-height:83vh;object-fit:contain;display:block}dialog .tools{display:flex;align-items:center;gap:12px;padding:8px 0;flex-wrap:wrap}dialog button{background:#fff1;border:1px solid #fff3;color:#fff;padding:8px 13px;border-radius:6px;cursor:pointer}dialog a{color:#b3ddce}#modal-title{flex:1}button:focus-visible,a:focus-visible{outline:3px solid #44c5ad;outline-offset:2px}@media(max-width:900px){.grid{grid-template-columns:1fr}.toolbar{position:static}.caption{padding:14px}header{padding-top:28px}}
</style><header><div class="eyebrow">SEJUKOPS / UI REVIEW / FICTIONAL OPERATIONS</div><h1>每一頁，每一個工作情境。</h1><p>使用 PR #39 的真實頁面樣式與 React 元件，搭配豐富的虛構馬來西亞營運資料。每張截圖均為 1920 × 1080（16:9）；長頁以分段截图呈現。點擊圖片可放大，使用 ← → 瀏覽，Esc 關閉。</p><div class="metrics"><span>__COUNT__ 張截圖</span><span>48 筆工單 · 12 個客戶 · 3 間分店</span><span>6 位技師 · 6 份知識文件 · 12 個員工</span><span>Admin / Manager / Technician</span></div></header><div class="toolbar"><input id="search" type="search" placeholder="搜尋頁面或功能，例如：排程、AI、知識" aria-label="搜尋截圖"><span class="count" id="count"></span><nav class="filters" aria-label="圖庫分類"><button data-filter="all" class="active">全部</button>__BUTTONS__</nav></div><main class="grid">__CARDS__</main><footer>所有客戶、工單、員工及 AI 回覆均為虛構的本機 Mock。登入、密碼及帳號頁只替換伺服器身份／動作邊界，保留原始頁面版型。這些截圖不代表真實登入、資料庫、付費模型或人工 UAT 已驗證。Native AI 回覆為腳本化資料快照。<a href="README.md">涵蓋範圍與驗證報告</a> · <a href="browser-results.json">瀏覽器紀錄</a></footer><dialog id="modal"><div class="tools"><button id="prev" aria-label="上一張">←</button><span id="modal-title"></span><button id="next" aria-label="下一張">→</button><a id="download" download>下載原圖</a><button id="close">關閉 ×</button></div><img id="modal-image" alt=""></dialog><script>
const shots=__DATA__;const cards=[...document.querySelectorAll('.card')];let filter='all',query='',current=0;const modal=document.getElementById('modal');function refresh(){let total=0;cards.forEach(c=>{const show=(filter==='all'||c.dataset.group===filter)&&c.dataset.search.toLowerCase().includes(query);c.hidden=!show;if(show)total++});document.getElementById('count').textContent=`顯示 ${total} / ${shots.length} 張`;}document.getElementById('search').oninput=e=>{query=e.target.value.trim().toLowerCase();refresh()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));refresh()});function show(i){current=(i+shots.length)%shots.length;const s=shots[current];const img=document.getElementById('modal-image');img.src=s.file;img.alt=s.title;document.getElementById('modal-title').textContent=`${current+1} / ${shots.length} · ${s.title}`;document.getElementById('download').href=s.file;if(!modal.open)modal.showModal();}document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>show(Number(b.dataset.index)));document.getElementById('prev').onclick=()=>show(current-1);document.getElementById('next').onclick=()=>show(current+1);document.getElementById('close').onclick=()=>modal.close();document.addEventListener('keydown',e=>{if(modal.open){if(e.key==='ArrowLeft')show(current-1);if(e.key==='ArrowRight')show(current+1)}});refresh();
</script></html>'''
page=page.replace('__COUNT__',str(len(shots))).replace('__BUTTONS__',buttons).replace('__CARDS__',''.join(cards)).replace('__DATA__',json.dumps(shots,ensure_ascii=False).replace('</','<\\/'))
(root/'index.html').write_text(page)
print('Gallery images:',len(shots),'all verified 1920x1080')
