import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const output=path.resolve(process.env.PORTAL_OUTPUT ?? '.agent/operations-portal-mock');fs.mkdirSync(output,{recursive:true});
// Actual components with fictional MSW APIs and synthetic navigation. No auth/live proof.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE ?? 'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='http://localhost:3200/workspaces/10000000-0000-4000-8000-000000000001';
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE ?? 'C:/Users/user/AppData/Local/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-win64/chrome-headless-shell.exe'});const p=await b.newPage({viewport:{width:1536,height:864}});let results=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
async function check(name,fn){await fn();results.push({name,status:'PASS'});console.log('PASS '+name)}
async function tab(name){await p.getByRole('navigation',{name:'Mock preview pages',exact:true}).getByRole('button',{name,exact:true}).click()}
async function visible(text){await p.getByText(text,{exact:false}).first().waitFor()}
async function select(label,option){await p.getByRole('combobox',{name:label,exact:true}).click(); await p.locator('.ant-select-item-option-content').getByText(option,{exact:true}).click()}
try{await p.route('**/*',route=>{const url=new URL(route.request().url()); return url.origin==='http://localhost:3200' ? route.continue() : route.abort();});await p.goto(base+'/overview');await visible('Visible recent orders');
await check('formal Admin overview and fixed navigation',async()=>{assert.equal(await p.getByRole('navigation',{name:'Workspace',exact:true}).getByRole('link',{name:'Assignment',exact:true}).count(),1);await visible('up to 20');});
await p.getByLabel('Mock persona').selectOption('guest-admin');await tab('Orders');await visible('MOCK-001');
await check('Guest Admin reads table without formal assignment navigation',async()=>{assert.equal(await p.getByRole('navigation',{name:'Workspace',exact:true}).getByRole('link',{name:'Assignment',exact:true}).count(),0);assert.equal(await p.getByRole('button',{name:'Create order',exact:true}).count(),0);await p.getByLabel('Search orders').fill('MOCK-002');await visible('MOCK-002');assert.equal(await p.getByRole('row').filter({hasText:'MOCK-001'}).count(),0);await p.getByLabel('Search orders').fill('');});
await check('on-demand New order Drawer creates fictional order',async()=>{await p.getByRole('button',{name:'New order',exact:true}).click(); await select('Branch','MOCK Fictional Workshop');await select('Existing customer','Fictional Customer');await p.getByLabel('Order number',{exact:true}).fill('PORTAL-MOCK-003');await p.getByLabel('Service type',{exact:true}).fill('Portal inspection');await p.getByLabel('Problem description',{exact:true}).fill('Fictional portal verification only');await p.getByRole('button',{name:'Create order',exact:true}).click();await visible('Order created');await p.getByRole('button',{name:'Close',exact:true}).click();await visible('PORTAL-MOCK-003');});
await check('Guest assignment Drawer updates visible order',async()=>{await p.getByRole('row').filter({hasText:'PORTAL-MOCK-003'}).getByRole('button',{name:'View details'}).click();await p.getByRole('button',{name:'Assign order',exact:true}).click();await select('Demo technician','Demo technician 1');await p.getByRole('button',{name:'Assign this order',exact:true}).click();await visible('Demo order assigned');await p.getByRole('button',{name:'Close',exact:true}).click();await p.locator('#workspace-order-detail').getByText('ASSIGNED',{exact:true}).waitFor();});
await check('AI Assist is opened on demand and can be dismissed',async()=>{await p.getByRole('button',{name:'AI Assist',exact:true}).click();await p.getByRole('dialog').waitFor();await p.getByRole('button',{name:'Close',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});});
await p.getByLabel('Mock persona').selectOption('guest-manager');await tab('Schedule');await visible('MOCK-002');
await check('Manager Schedule includes unscheduled attention and opens reschedule Drawer',async()=>{await p.getByRole('heading',{name:'Schedule',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'New order',exact:true}).count(),0);await p.getByRole('row').filter({hasText:'MOCK-002'}).getByRole('button',{name:'View details'}).click();await p.getByRole('button',{name:'Reschedule order',exact:true}).click();const date=p.getByRole('textbox',{name:'New scheduled time',exact:true});await date.fill('2026-10-01 11:30');await date.press('Enter');await p.getByText('Review MOCK-002:',{exact:false}).waitFor();await p.getByRole('button',{name:'Confirm new schedule',exact:true}).click();await visible('Schedule changed');await p.getByRole('button',{name:'Close',exact:true}).click();await p.locator('#workspace-order-detail').getByText(/11:30/).waitFor();});
await p.getByLabel('Mock persona').selectOption('guest-technician');await tab('Orders');await visible('MOCK-002');
await check('Technician portal manual start/complete and restricted controls',async()=>{await p.getByRole('heading',{name:'My jobs',exact:true}).waitFor();assert.equal(await p.getByRole('navigation',{name:'Interaction mode'}).getByRole('link',{name:'AI Workspace',exact:true}).count(),0);assert.equal(await p.getByRole('button',{name:'New order',exact:true}).count(),0);await p.getByRole('row').filter({hasText:'MOCK-002'}).getByRole('button',{name:'View details'}).click();await p.getByRole('button',{name:'Start assigned job',exact:true}).click();await p.getByRole('button',{name:'Complete job',exact:true}).waitFor();await p.getByRole('button',{name:'Complete job',exact:true}).click();await p.locator('#workspace-order-detail').getByText('COMPLETED',{exact:true}).waitFor();});
await p.screenshot({path:output+'/technician.png',fullPage:true});
await check('mobile page contains no document overflow',async()=>{await p.setViewportSize({width:390,height:844});await p.waitForTimeout(250);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));});
await p.getByLabel('Mock scenario').selectOption('server-error');await tab('Overview');await visible('Overview could not be loaded.');results.push({name:'safe overview failure',status:'PASS'});
await p.getByLabel('Mock scenario').selectOption('empty');await visible('No recent assigned jobs');results.push({name:'empty Technician overview',status:'PASS'});

await p.setViewportSize({width:1536,height:864});await p.getByLabel('Mock persona').selectOption('guest-admin');await p.getByLabel('Mock scenario').selectOption('delayed');await tab('Orders');await visible('MOCK-001');
await check('pending manual creation keeps Drawer open and prevents duplicate submit',async()=>{await p.getByRole('button',{name:'New order',exact:true}).click();await select('Branch','MOCK Fictional Workshop');await select('Existing customer','Fictional Customer');await p.getByLabel('Order number',{exact:true}).fill('PORTAL-DELAYED');await p.getByLabel('Service type',{exact:true}).fill('Fictional delayed test');await p.getByLabel('Problem description',{exact:true}).fill('Synthetic pending write');await p.getByRole('button',{name:'Create order',exact:true}).click();await p.waitForTimeout(150);assert.equal(await p.getByRole('button',{name:'Close',exact:true}).count(),0);assert(await p.getByRole('button',{name:'Create order',exact:true}).isDisabled());await p.keyboard.press('Escape');await p.getByRole('dialog').waitFor();await visible('Order created in this workspace.');await p.getByRole('button',{name:'Close',exact:true}).click();await visible('PORTAL-DELAYED');});
await p.getByLabel('Mock scenario').selectOption('stale-write');await p.getByLabel('Mock persona').selectOption('guest-manager');await tab('Schedule');await visible('MOCK-002');
await check('stale schedule is rejected without a success claim',async()=>{await p.getByRole('row').filter({hasText:'MOCK-002'}).getByRole('button',{name:'View details'}).click();await p.getByRole('button',{name:'Reschedule order',exact:true}).click();const date=p.getByRole('textbox',{name:'New scheduled time',exact:true});await date.fill('2026-10-01 11:30');await date.press('Enter');await p.getByRole('button',{name:'Confirm new schedule',exact:true}).click();await visible('The order or Demo data changed.');assert.equal(await p.getByText('Schedule changed. The assigned technician is unchanged.',{exact:true}).count(),0);await p.getByRole('button',{name:'Close',exact:true}).click();await p.locator('#workspace-order-detail').getByText(/10:00/).waitFor();});

await p.getByLabel('Mock scenario').selectOption('success');await p.getByLabel('Mock persona').selectOption('staff-admin');await tab('Assignment');
await check('formal Admin saved proposal shows business order and MYT then executes',async()=>{await select('Order','MOCK-001 (NEW)');await select('Technician for this branch','Technician 40000000');const date=p.getByRole('textbox',{name:'Scheduled time (optional)',exact:true});await date.fill('2026-10-06 11:30');await date.press('Enter');await p.getByRole('button',{name:'Prepare proposal',exact:true}).click();const card=p.getByLabel('Saved assignment proposal');await card.getByText('PENDING',{exact:true}).waitFor();await card.getByText('MOCK-001',{exact:true}).waitFor();await card.getByText(/11:30.*MYT/).waitFor();await p.getByRole('button',{name:'Confirm and execute this assignment',exact:true}).click();await card.getByText('EXECUTED',{exact:true}).waitFor();await visible('Assignment executed.');});
assert.deepEqual(errors,[]);
}catch(e){results.push({name:'runner',status:'FAIL',message:e.message});console.error(e);console.log((await p.locator('body').innerText()).slice(-4500));await p.screenshot({path:output+'/failure.png',fullPage:true});process.exitCode=1}finally{fs.writeFileSync(output+'/browser.json',JSON.stringify({results,errors},null,2));await b.close()}})();
