import { createRequire } from 'node:module';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.UI_PLAYWRIGHT_PATH || '/opt/codex/cua_node/lib/node_modules/playwright');
const output=path.resolve(process.env.UI_GALLERY_OUTPUT || 'reports/ui-mock-gallery');
await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.UI_CHROMIUM_PATH || '/usr/bin/chromium',args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1});
const only=(process.env.UI_GALLERY_ONLY||"").split("|").filter(Boolean);
let previous; if(only.length)previous=JSON.parse(await fs.readFile(path.join(output,"browser-results.json"),"utf8"));
const evidence=previous ?? {viewport:{width:1920,height:1080},scope:'Actual product markup/components with local fictional MSW data; server identity/actions adapted for public/account pages. No live Auth/database/provider calls or Human UAT.',screenshots:[],checks:[],failures:[],pageErrors:[],externalRequests:[]};
const origin='http://localhost:3200',base='/workspaces/10000000-0000-4000-8000-000000000001';
await context.route('**/*',async route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&u.origin!==origin){evidence.externalRequests.push(u.origin+u.pathname);await route.abort();}else await route.continue();});
const page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',error=>evidence.pageErrors.push(error.message));
const style='.mock-controls,.mock-footer{display:none!important}body::after{content:"MOCK · 虛構營運資料 · 1920 × 1080";position:fixed;right:12px;bottom:8px;background:#fff4cc;border:1px solid #eed58e;color:#60440d;padding:4px 9px;border-radius:4px;font:11px system-ui;z-index:99999;pointer-events:none}';
if(previous){evidence.failures.forEach(f=>{if(f.name==="Dashboard insight")f.name="Dashboard Ask AI";});evidence.failures=evidence.failures.filter(f=>!only.includes(f.name));evidence.checks=evidence.checks.filter(c=>!only.includes(c.name));evidence.screenshots=evidence.screenshots.filter(s=>!s.title.startsWith('未完成：'));}
let nextShot=Math.max(0,...evidence.screenshots.map(s=>Number(s.file.split('-')[0])))+1;
let group='';
async function open(tab,persona='owner-admin',scenario='realistic',query=''){
 await page.goto(`${origin}${base}/${tab}?scenario=${scenario}&persona=${persona}${query?'&'+query:''}`);
 await page.locator('.mock-controls').waitFor();await page.addStyleTag({content:style});
 await page.waitForTimeout(350);assert.equal(await page.locator('.mock-fatal').count(),0,'Preview renders');
}
async function shot(slug,title,{bottom=false}={}){
 await page.evaluate(()=>document.activeElement?.blur());await page.waitForTimeout(250);
 if(bottom)await page.evaluate(()=>{const main=document.querySelector(".desktop-content"); if(main)main.scrollTop=main.scrollHeight; else window.scrollTo(0,document.documentElement.scrollHeight);});
 const filename=`${String(nextShot++).padStart(3,'0')}-${slug}.png`;
 await page.screenshot({path:path.join(output,filename),fullPage:false,animations:'disabled'});
 evidence.screenshots.push({file:filename,title,group,route:new URL(page.url()).pathname,persona:await page.getByLabel('Mock persona').inputValue(),scenario:await page.getByLabel('Mock scenario').inputValue()});
 console.log('CAPTURE',filename,title);
}
async function lower(slug,title){if(await page.evaluate(()=>{const main=document.querySelector(".desktop-content");return main ? main.scrollHeight>main.clientHeight+60 : document.documentElement.scrollHeight>innerHeight+60;}))await shot(slug,title,{bottom:true});}
async function feature(name,action){if(only.length&&!only.includes(name))return;try{await action();evidence.checks.push({name,result:'PASS'});}catch(error){evidence.failures.push({name,error:error.message});console.error('FAIL',name,error.message);await shot('failure',`未完成：${name}`).catch(()=>{});}}
async function select(label,index=0){const input=page.getByRole('combobox',{name:label,exact:true});await input.waitFor({state:'visible'});await page.waitForFunction(element=>!element.disabled,await input.elementHandle());await input.focus();for(let i=0;i<=index;i++){await input.press('ArrowDown');await page.waitForTimeout(80);}await input.press('Enter');await page.waitForTimeout(100);}
async function detail(index=0){await page.getByRole('button',{name:'View details',exact:true}).nth(index).click();await page.getByRole('dialog',{name:'Order detail',exact:true}).waitFor();}
async function agent(prompt){await page.getByRole('button',{name:'Open conversation',exact:true}).click();const panel=page.getByRole('region',{name:'Agent conversation',exact:true});await panel.getByRole('textbox',{name:'Message the agent',exact:true}).fill(prompt);await panel.getByRole('button',{name:'Send message',exact:true}).click();await page.locator('[data-agent-view]').waitFor();await page.waitForTimeout(300);}
try{
 group='入口與帳號';
 for(const [tab,title] of [['home','產品首頁'],['staff-login','員工登入'],['owner-login','Owner 登入'],['demo-entry','Guest Demo 入口'],['owner-account','Owner 帳號與管理入口'],['owner-password','Owner 修改密碼'],['staff-password','員工首次設定密碼'],['access-denied','無權限頁面']])await feature(title,async()=>{await open(tab);await shot(tab,title);await lower(tab+'-lower',title+' · 下半頁');});
 await feature('登入錯誤與密碼成功',async()=>{await open('staff-login','owner-admin','realistic','error=invalid');await shot('login-error','登入失敗提示');await open('staff-password');await page.getByLabel('Current password',{exact:true}).fill('Mock-current-42');await page.getByLabel('New password',{exact:true}).fill('Mock-new-password-42');await page.getByLabel('Confirm new password',{exact:true}).fill('Mock-new-password-42');await page.getByRole('button',{name:'Change password',exact:true}).click();await page.getByText('Password changed. Sign in again to open your workspace.').waitFor();await shot('password-success','員工密碼設定完成 · Mock');});
 group='Dashboard';
 for(const [persona,title] of [['guest-admin','Admin'],['guest-manager','Manager'],['guest-technician','Technician']])await feature(title+' dashboard',async()=>{await open('overview',persona);await page.getByRole('heading',{name:/Dashboard|Overview/i}).first().waitFor();await page.locator('.dashboard-panel').first().waitFor();await shot(persona+'-dashboard',title+' 營運儀表板');await lower(persona+'-dashboard-lower',title+' 圖表、工作量與近期工單');});
 await feature('Dashboard Ask AI',async()=>{await open('overview');await page.getByRole("button",{name:"Open Operations Ask AI",exact:true}).click();const panel=page.getByRole("dialog",{name:"Operations · Ask AI",exact:true});await panel.getByRole("textbox",{name:"Question",exact:true}).fill("Show current orders and visits");await panel.getByRole("button",{name:"Ask AI",exact:true}).click();await panel.getByRole("region",{name:"Orders from scoped evidence",exact:true}).waitFor();await shot("dashboard-insight","儀表板 · Ask AI 重點摘要");});
 group='工單與排程';
 await feature('Order browse/filter/detail',async()=>{await open('orders');await page.getByText('SJ-KL-2610-001',{exact:true}).waitFor();await shot('orders','Admin 工單清單 · 48 筆');await page.getByRole('button',{name:/IN PROGRESS/}).click();await shot('orders-filter','進行中工單篩選');await open('orders');await detail();await shot('order-detail','工單詳情 · 症狀、現場地址與操作');});
 await feature('Create order',async()=>{await open('orders');await page.getByRole('button',{name:'New order',exact:true}).click();await select('Branch');await select('Existing customer');await page.getByLabel('Order number',{exact:true}).fill('SJ-KL-2610-049');await page.getByLabel('Service type',{exact:true}).fill('Preventive maintenance');await page.getByLabel('Problem description',{exact:true}).fill('Meranti Residence — Service two bedroom split units. Confirm access with reception after 10:00; inspect filters, drainage and outdoor clearance.');await shot('order-create','新增工單 · 完整填寫');await page.getByRole('button',{name:'Create order',exact:true}).click();await page.getByText('Order created in this workspace.',{exact:true}).waitFor();await shot('order-create-success','新增工單完成 · Mock');});
 await feature('Document intake',async()=>{await open('orders');await page.getByRole('button',{name:'Import document',exact:true}).click();await shot('intake-upload','文件匯入 · 上傳');await page.locator('input[type=file]').first().setInputFiles({name:'Meranti-service-request.txt',mimeType:'text/plain',buffer:Buffer.from('Meranti Residence requests air-conditioning inspection on 7 October 2026. Quoted RM180; confirm quotation and access.')});await page.getByRole('button',{name:/Extract|Read document|Prepare draft/}).first().click();await page.waitForTimeout(500);await shot('intake-review','文件抽取 · 欄位信心與待確認事項');const d=page.locator('.ant-drawer-body:visible').first();await d.evaluate(e=>e.scrollTop=e.scrollHeight);await shot('intake-review-lower','文件抽取 · 確認與建立工單');});
 for(const [persona,title] of [['guest-admin','Admin'],['guest-manager','Manager'],['guest-technician','Technician']])await feature(title+' schedule',async()=>{await open('schedule',persona);await page.getByRole('button',{name:'View details',exact:true}).first().waitFor();await shot(persona+'-schedule',title+' 排程與待安排訪視');});
 await feature('Guest assignment',async()=>{await open('orders','guest-admin');await detail();await page.getByRole('button',{name:'Assign order',exact:true}).click();await shot('guest-assignment','Guest Admin · 指派技師');});
 await feature('Manager reschedule',async()=>{await open('orders','guest-manager');await detail(1);await page.getByRole('button',{name:'Reschedule order',exact:true}).click();await shot('manager-reschedule','Manager · 重新安排訪視');});
 await feature('Technician progress',async()=>{await open('orders','guest-technician');await page.getByRole('button',{name:'View details',exact:true}).first().waitFor();await shot('technician-jobs','Technician · 我的工作');await detail();await shot('technician-job-detail','Technician · 現場工作與開始操作');await page.getByRole('button',{name:'Start assigned job',exact:true}).click();await page.getByRole('button',{name:'Complete job',exact:true}).waitFor();await shot('technician-job-started','Technician · 工作進行中');await page.getByRole('button',{name:'Complete job',exact:true}).click();await page.waitForTimeout(400);await shot('technician-job-completed','Technician · 完成工作');});
 await feature('Saved assignment',async()=>{await open('assignment');await select('Order');await select('Technician for this branch');await shot('assignment-prepare','正式指派 · 準備提案');await page.getByRole('button',{name:'Prepare proposal',exact:true}).click();await page.getByRole('region',{name:'Saved assignment proposal'}).waitFor().catch(()=>page.getByText('Review saved proposal',{exact:true}).waitFor());await shot('assignment-review','正式指派 · 檢查已保存提案');await lower('assignment-review-lower','正式指派 · 明確確認');await page.getByRole('button',{name:'Confirm and execute this assignment',exact:true}).click();await page.getByText('Assignment executed.',{exact:true}).waitFor();await shot('assignment-executed','正式指派 · 執行結果');});
 group='AI Assist 與 AI Workspace';
 await feature('Order AI Assist',async()=>{await open('orders');await detail();await page.getByRole('button',{name:'AI Assist',exact:true}).click();await shot('order-ai-assist','單一工單 AI Assist');await page.getByRole('button',{name:/Check orders$/}).click();await page.getByText(/MOCK evidence:/).waitFor();await shot('order-ai-result','單一工單 AI Assist · 檢查結果');});
 for(const [persona,title] of [['guest-admin','Admin'],['guest-manager','Manager'],['guest-technician','Technician']])await feature(title+' Ask AI',async()=>{await open('overview',persona);await page.getByRole('button',{name:'Open Operations Ask AI',exact:true}).click();const d=page.getByRole('dialog',{name:'Operations · Ask AI',exact:true});await d.getByRole('textbox',{name:'Question',exact:true}).fill('Show my jobs and filter knowledge');await d.getByRole('button',{name:'Ask AI',exact:true}).click();await d.getByRole('region',{name:'Cited knowledge excerpts',exact:true}).waitFor();await shot(persona+'-ask-ai',title+' · Ask AI 對話、工單與引用');});
 await feature('Agent landing',async()=>{await open('agent','guest-admin');await shot('agent-home','AI Workspace · 任務入口');});
 for(const [view,prompt,title] of [['focus','Which recent orders need attention?','工作焦點'],['investigation','Investigate details for SJ-KL-2610-001 [[view:investigation]]','工單調查'],['comparison','Compare SJ-KL-2610-001 and SJ-PJ-2610-002','工單比較'],['knowledge','Find published filter inspection guidance','知識檢索'],['clarification','Clarify a request with missing information','補充資訊']])await feature('Agent '+view,async()=>{await open('agent','guest-admin');await agent(prompt);await shot('agent-'+view,'AI Workspace · '+title);await page.getByRole('button',{name:'Minimize conversation',exact:true}).click();await shot('agent-'+view+'-canvas','AI 工作畫布 · '+title);await lower('agent-'+view+'-lower','AI 工作畫布 · '+title+'下半頁');});
 await feature('Agent proposal',async()=>{await open('agent');await agent('Prepare an assignment for SJ-KL-2610-001 [[prepare-assignment]]');await page.getByRole('button',{name:'Minimize conversation',exact:true}).click();await shot('agent-proposal','AI 提案 · 待明確批准');await lower('agent-proposal-lower','AI 提案 · 確認區域');});
 await feature('Agent execution and cancel',async()=>{await open('agent','guest-admin','delayed');await page.getByRole('button',{name:'Open conversation',exact:true}).click();const p=page.getByRole('region',{name:'Agent conversation',exact:true});await p.getByRole('textbox',{name:'Message the agent',exact:true}).fill('Compare MOCK-001 and MOCK-002');await p.getByRole('button',{name:'Send message',exact:true}).click();await p.getByRole('region',{name:'Agent execution',exact:true}).getByText('Read recent orders',{exact:true}).waitFor();await shot('agent-running','AI 執行中 · 即時工具活動');await p.getByRole('button',{name:'Cancel request',exact:true}).click();await shot('agent-cancelled','AI 取消請求');});
 group='知識庫';
 await feature('Knowledge search',async()=>{await open('knowledge');await shot('knowledge-search','知識庫 · 搜尋入口');await page.getByLabel('Search text',{exact:true}).fill('filter drainage installation');await page.getByRole('button',{name:'Search',exact:true}).click();await page.locator('.workspace-result').first().waitFor();await shot('knowledge-results','知識搜尋 · 發布文件與來源引用');await lower('knowledge-results-lower','知識搜尋 · 更多來源');});
 await feature('Knowledge create/stage/index/publish',async()=>{await open('knowledge');await page.getByRole('tab',{name:'Manage knowledge',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Clinic quarterly maintenance checklist');await page.getByLabel('Source label',{exact:true}).fill('Operations handbook · Clinics / Rev 2');await shot('knowledge-create','知識管理 · 新增私人草稿');await page.getByRole('button',{name:'Create draft',exact:true}).click();await page.getByLabel('Knowledge text',{exact:true}).fill('Confirm the clinic contact and agree on an isolation area before work. Inspect all three air-conditioning units, protect examination equipment, clean reusable filters and check condensate drainage. Record supply temperatures after stable operation and report any unresolved symptoms before leaving.');await shot('knowledge-source','知識管理 · 文字與 PDF 來源');await page.getByRole('button',{name:'Add text for review',exact:true}).click();await page.getByText('PENDING',{exact:true}).waitFor();await shot('knowledge-pending','知識管理 · 待索引審閱');await lower('knowledge-pending-lower','知識管理 · 來源與搜尋準備');await page.getByRole('button',{name:'Prepare for search',exact:true}).click();await page.getByRole('button',{name:'Publish this reviewed version',exact:true}).waitFor();await shot('knowledge-ready','知識管理 · 索引完成、準備發布',{bottom:true});await page.getByRole('button',{name:'Publish this reviewed version',exact:true}).click();await shot('knowledge-published','知識管理 · 已發布',{bottom:true});});
 group='AI 平台設定';
 await feature('AI settings providers and routing',async()=>{await open('ai-settings');await page.getByText('Operations · Fast reasoning',{exact:true}).waitFor();await shot('ai-settings','AI 供應商 · 多模型設定');await lower('ai-settings-routing','按任務路由與能力相容性');await page.getByText('Single Model',{exact:true}).click();await shot('ai-settings-single','單一模型路由',{bottom:true});});
 await feature('AI provider editor',async()=>{await open('ai-settings');await page.getByRole('button',{name:/Edit$/}).first().click();await shot('provider-edit','編輯模型 · URL、憑證與能力');await page.getByRole('button',{name:/Test saved profile$/}).click();await page.waitForTimeout(400);await shot('provider-test','模型連線測試結果 · Mock');});
 await feature('Add and remove provider',async()=>{await open('ai-settings');await page.getByRole('button',{name:/Add provider$/}).click();await page.getByLabel('Profile name',{exact:true}).fill('Service desk · Balanced reasoning');await page.getByLabel('Base URL',{exact:true}).fill('https://balanced.models.example/v1');await page.getByLabel('Model',{exact:true}).fill('balanced-reasoner-v1');await page.getByPlaceholder('Enter provider API key',{exact:true}).fill('FICTIONAL-ONLY-NOT-A-KEY');await shot('provider-create','新增模型 · 表單');await page.getByRole('dialog').getByRole('button',{name:/Add provider$/}).click();await page.getByText('Service desk · Balanced reasoning',{exact:true}).waitFor();await shot('provider-created','新增模型完成 · Mock');await open('ai-settings');await page.getByRole('button',{name:/Remove$/}).last().click();await shot('provider-remove','移除模型 · 確認提示');});
 group='員工與 Owner 預覽';
 await feature('Staff list/editor',async()=>{await open('staff');await page.getByText('Alicia Tan',{exact:true}).waitFor();await shot('staff','員工清單 · 角色、分店與入職狀態');await lower('staff-import-panel','員工清單 · Excel 匯入');await page.getByRole('button',{name:'Create staff account',exact:true}).click();await page.getByLabel('Employee name',{exact:true}).fill('Emily Chan');await page.getByLabel('Employee email',{exact:true}).fill('emily.chan@sejuk-demo.example');await shot('staff-create','建立員工帳號');await page.getByRole('button',{name:'Create account',exact:true}).click();await page.getByText('Staff account created.',{exact:true}).waitFor();await shot('staff-created','員工建立結果 · Mock 臨時密碼');});
 await feature('Staff edit/disable',async()=>{await open('staff');await page.getByRole('button',{name:'Edit Ahmad Hakim',exact:true}).click();await shot('staff-edit','編輯員工角色與分店');await page.getByRole('switch',{name:'Account active',exact:true}).click();await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('dialog',{name:'Disable employee access?',exact:true}).waitFor();await shot('staff-disable','停用員工存取 · 確認');});
 await feature('Staff password reset',async()=>{await open('staff');await page.getByRole('button',{name:'Reset temporary password for Alicia Tan',exact:true}).click();await shot('staff-password-reset','重設員工臨時密碼 · 確認');await page.getByRole('button',{name:'Reset password',exact:true}).click();await page.waitForTimeout(300);await shot('staff-password-result','重設員工臨時密碼 · Mock 結果');});
 await feature('Staff import review',async()=>{await open('staff');await page.getByLabel('Staff workbook (.xlsx)',{exact:true}).setInputFiles({name:'staff-onboarding.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from('MOCK WORKBOOK - scripted adapter, not parser evidence')});await page.getByRole('dialog',{name:'Review staff import',exact:true}).waitFor();await shot('staff-import-preview','Excel 員工匯入 · 預覽與逐列驗證');await page.getByRole('button',{name:'Confirm import',exact:true}).click();await page.getByText('Import finished: 2 successful · 0 failed.',{exact:true}).waitFor();await shot('staff-import-result','Excel 員工匯入 · Mock 結果');});
 await feature('Owner read-only preview',async()=>{await open('owner-account');await page.getByRole('button',{name:'Open read-only preview',exact:true}).click();await page.waitForTimeout(750);await shot('owner-preview','Owner · 唯讀 Admin 視角');});
 group='Demo 管理與診斷';
 await feature('Platform reset/budget',async()=>{await open('platform');await page.getByText('Demo orders',{exact:true}).waitFor();await shot('platform','Demo 管理 · 48 工單與重設控制');await page.getByLabel('Type RESET DEMO to confirm',{exact:true}).fill('RESET DEMO');await shot('platform-reset-confirm','Demo 重設 · 明確確認');await page.getByRole('button',{name:'Reset Demo',exact:true}).click();await page.waitForTimeout(400);await shot('platform-reset-result','Demo 重設 · 新世代與保留設定');});
 await feature('Diagnostics traces',async()=>{await open('diagnostics');await page.getByText('Read scoped service orders',{exact:true}).first().waitFor();await shot('diagnostics','AI 觀測 · 執行狀態、Tokens 與延遲');await lower('diagnostics-lower','AI 觀測 · 分頁與完整紀錄');await page.getByRole('button',{name:'Read scoped service orders',exact:true}).first().click();await page.getByRole('heading',{name:'Execution trace',exact:true}).waitFor();await shot('diagnostics-detail','AI 觀測 · 執行追蹤詳情');});
 await feature('Guest AI budget settings',async()=>{await open('ai-settings');await page.getByLabel('Daily paid AI call limit',{exact:true}).waitFor();await shot('guest-budget','共用 Guest AI 額度 · 每日用量與上限',{bottom:true});await page.getByLabel('Daily paid AI call limit',{exact:true}).fill('35');await page.getByRole('button',{name:'Save limit',exact:true}).click();await page.waitForTimeout(400);await shot('guest-budget-updated','共用 Guest AI 額度 · 更新上限',{bottom:true});});
 group='更多功能狀態';
 await feature('New customer and calendar',async()=>{await open('orders');await page.getByRole('button',{name:'New order',exact:true}).click();await select('Customer mode',1);await page.getByLabel('Customer name',{exact:true}).fill('Bunga Raya Wellness');await page.getByLabel('Customer address',{exact:true}).fill('29 Jalan SS 15/4, Subang Jaya');await shot('order-new-customer','新增工單 · 新客戶資料');await open('orders','guest-manager');await detail(1);await page.getByRole('button',{name:'Reschedule order',exact:true}).click();await page.getByRole('textbox',{name:'New scheduled time',exact:true}).click();await shot('schedule-calendar','排程 · 日期與時間選擇器');});
 await feature('Intake confirmation',async()=>{await open('orders');await page.getByRole('button',{name:'Import document',exact:true}).click();await page.locator('input[type=file]').first().setInputFiles({name:'service-request.txt',mimeType:'text/plain',buffer:Buffer.from('Fictional service request')});await page.getByRole('button',{name:'Extract draft',exact:true}).click();await page.getByRole('combobox',{name:'Existing branch',exact:true}).waitFor();await select('Existing branch');await select('Existing customer');await page.getByLabel('Order number',{exact:true}).fill('SJ-KL-2610-050');await page.getByRole('button',{name:'Confirm and create this order',exact:true}).click();await page.getByText('Order created',{exact:true}).waitFor();await shot('intake-confirmed','文件轉工單 · 確認完成');});
 await feature('Knowledge PDF staging',async()=>{await open('knowledge');await page.getByRole('tab',{name:'Manage knowledge',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Quarterly service PDF checklist');await page.getByLabel('Source label',{exact:true}).fill('Field handbook / Rev 4');await page.getByRole('button',{name:'Create draft',exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'quarterly-service.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 fictional local adapter')});await shot('knowledge-pdf-upload','知識管理 · PDF 已選取');await page.getByRole('button',{name:'Add PDF text for review',exact:true}).click();await page.getByText('Text-native PDF',{exact:true}).waitFor();await shot('knowledge-pdf-review','知識管理 · PDF 文字審閱',{bottom:true});});
 await feature('Native proposal confirmation',async()=>{await open('agent');await agent('Prepare an assignment for SJ-KL-2610-001 [[prepare-assignment]]');await page.getByRole('button',{name:'Minimize conversation',exact:true}).click();await page.getByRole('button',{name:'Confirm and execute assignment',exact:true}).click();await page.getByText('EXECUTED',{exact:true}).waitFor();await shot('agent-confirmed','AI 提案 · 已確認執行的 Mock 結果',{bottom:true});});
 await feature('Stale proposal',async()=>{await open('assignment','owner-admin','stale-write');await select('Order');await select('Technician for this branch');await page.getByRole('button',{name:'Prepare proposal',exact:true}).click();await page.getByRole('button',{name:'Confirm and execute this assignment',exact:true}).waitFor();await page.getByRole('button',{name:'Confirm and execute this assignment',exact:true}).click();await page.getByText('STALE',{exact:true}).waitFor();await shot('assignment-stale','指派提案 · 資料變更後拒絕執行',{bottom:true});});
 await feature('Owner Technician preview',async()=>{await open('owner-account');await select('Business perspective',2);await select('Technician employee');await shot('owner-technician-choice','Owner · 選擇技師視角');await page.getByRole('button',{name:'Open read-only preview',exact:true}).click();await page.getByText(/Read-only Technician preview/).waitFor();await shot('owner-technician-preview','Owner · 技師唯讀視角');});
 await feature('Knowledge index failure',async()=>{await open('knowledge','owner-admin','index-failed','reviewDocumentId=60000000-0000-4000-8000-000000000001&reviewVersionId=70000000-0000-4000-8000-000000000001');await page.getByRole('button',{name:'Retry failed index',exact:true}).waitFor();await shot('knowledge-index-failed','知識管理 · 索引失敗與重試',{bottom:true});await page.getByRole('button',{name:'Retry failed index',exact:true}).click();await page.getByRole('button',{name:'Prepare for search',exact:true}).waitFor();await shot('knowledge-index-retry','知識管理 · 重試後待準備搜尋',{bottom:true});});
 await feature('Diagnostics filters',async()=>{await open('diagnostics');await page.getByRole('combobox').nth(1).focus();await page.getByRole('combobox').nth(1).press('ArrowDown');await page.getByRole('combobox').nth(1).press('ArrowDown');await page.getByRole('combobox').nth(1).press('ArrowDown');await page.getByRole('combobox').nth(1).press('Enter');await page.waitForTimeout(400);await shot('diagnostics-filter','AI 觀測 · 狀態篩選');});
 group='空白、錯誤與額度狀態';
 for(const [tab,scenario,title] of [['orders','empty','工單空白狀態'],['orders','server-error','工單載入失敗'],['knowledge','empty','知識庫空白狀態'],['ai-settings','server-error','AI 設定載入失敗'],['staff','empty','員工空白狀態']])await feature(title,async()=>{await open(tab,'owner-admin',scenario);await page.waitForTimeout(300);await shot(tab+'-'+scenario,title);});
 await feature('AI quota',async()=>{await open('agent','guest-admin','quota-exhausted');await page.getByRole('button',{name:'Open conversation',exact:true}).click();const p=page.getByRole('region',{name:'Agent conversation',exact:true});await p.getByRole('textbox',{name:'Message the agent',exact:true}).fill('Show recent orders');await p.getByRole('button',{name:'Send message',exact:true}).click();await page.getByText(/Today's Guest AI allowance is used up/).first().waitFor();await shot('agent-quota','AI 額度用盡 · 保留手動操作');});
}finally{
 await browser.close();evidence.result=evidence.failures.length||evidence.pageErrors.length||evidence.externalRequests.length?'FAIL':'PASS';
 await fs.writeFile(path.join(output,'browser-results.json'),JSON.stringify(evidence,null,2));
 console.log('RESULT',evidence.result,'screenshots',evidence.screenshots.length,'failed journeys',evidence.failures.length);
 if(evidence.result==='FAIL')process.exitCode=1;
}
