import "server-only";

import ExcelJS from "exceljs";
import { fromBuffer, type Entry, type ZipFile } from "yauzl";
import type { Readable } from "node:stream";
import {
  STAFF_IMPORT_MAX_BYTES,
  STAFF_IMPORT_MAX_ROWS,
  staffAccountInputSchema,
  type StaffImportPreview,
  type StaffImportRow,
} from "@/domain/staff/contracts";

const HEADERS = ["name", "email", "role", "branchCode"] as const;
const MAX_EXPANDED_BYTES = 8 * 1024 * 1024;
const MAX_ENTRY_BYTES = 2 * 1024 * 1024;
const MAX_ENTRIES = 128;
const PREFLIGHT_TIMEOUT_MS = 5_000;
// Bound sparse coordinates as well as bytes before ExcelJS allocates row/cell arrays.
const MAX_PHYSICAL_ROW = 1_001;
const MAX_PHYSICAL_COLUMN = 32;
const FILE_ERROR = "Use a valid, unencrypted .xlsx Staff template without formulas, macros, or external links.";

function invalidWorkbook(): Error {
  // Never forward parser errors that can include uploaded content or file paths.
  return new Error(FILE_ERROR);
}

function decodeXmlReferences(xml: string): string {
  return xml.replace(/&#(?:x([0-9a-f]+)|(\d+));/gi, (_, hex: string, decimal: string) => {
    const code = Number.parseInt(hex ?? decimal, hex ? 16 : 10);
    return code <= 0x10ffff ? String.fromCodePoint(code) : "";
  });
}

function inspectXml(name: string, bytes: Buffer): void {
  // OOXML generated by Excel/our template is UTF-8. Reject alternate encodings
  // rather than let security inspection and the downstream XML reader disagree.
  if (bytes.includes(0)) throw invalidWorkbook();
  const xml = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  const declaredEncoding = xml.match(/<\?xml\b[^?]*\bencoding\s*=\s*["']([^"']+)["']/i)?.[1];
  if (declaredEncoding && !/^utf-?8$/i.test(declaredEncoding)) throw invalidWorkbook();
  if (/<!\s*(?:DOCTYPE|ENTITY)\b/i.test(xml)) throw invalidWorkbook();
  const decoded = decodeXmlReferences(xml);
  if (/\b(?:ContentType|Type)\s*=\s*["'][^"']*(?:macroenabled|vbaproject|externallink|oleobject|\/relationships\/hyperlink)/i.test(decoded)
    || /\bTargetMode\s*=\s*["']\s*External\s*["']/i.test(decoded)) throw invalidWorkbook();
  if (name === "xl/workbook.xml") {
    const sheetIds = new Set<number>();
    for (const match of decoded.matchAll(/<sheet\b([^>]*)>/g)) {
      const rawId = match[1].match(/\bsheetId\s*=\s*["']([^"']+)["']/)?.[1];
      const id = Number(rawId);
      if (!rawId || !/^\d+$/.test(rawId) || id < 1 || id > MAX_ENTRIES || sheetIds.has(id)) throw invalidWorkbook();
      sheetIds.add(id);
    }
    if (sheetIds.size < 1 || sheetIds.size > 2) throw invalidWorkbook();
  }
  if (/^xl\/worksheets\//.test(name)) {
    if (/<(?:[\w.-]+:)?f(?:\s|\/?>)/i.test(xml)) throw invalidWorkbook();
    // Unsupported layout features can hide/repeat cells; fail before importing.
    if (/<(?:[\w.-]+:)?(?:mergeCell|hyperlink|tablePart|drawing|oleObject)(?:\s|\/?>)/i.test(xml)) {
      throw invalidWorkbook();
    }
    for (const match of decoded.matchAll(/<row\b[^>]*\br\s*=\s*["']([^"']+)["']/g)) {
      if (!/^\d+$/.test(match[1]) || Number(match[1]) < 1 || Number(match[1]) > MAX_PHYSICAL_ROW) {
        throw invalidWorkbook();
      }
    }
    for (const match of decoded.matchAll(/<c\b[^>]*\br\s*=\s*["']([^"']+)["']/g)) {
      const coordinate = /^([A-Z]+)([1-9]\d*)$/.exec(match[1]);
      if (!coordinate) throw invalidWorkbook();
      let column = 0;
      for (const letter of coordinate[1]) column = column * 26 + letter.charCodeAt(0) - 64;
      if (column > MAX_PHYSICAL_COLUMN || Number(coordinate[2]) > MAX_PHYSICAL_ROW) throw invalidWorkbook();
    }
    // Row/cell declarations without coordinates, duplicate/out-of-order coordinates
    // are not part of the accepted template format and may overwrite hidden values.
    let previousRow = 0;
    for (const match of decoded.matchAll(/<row\b([^>]*)>/g)) {
      const row = Number(match[1].match(/\br\s*=\s*["'](\d+)["']/)?.[1]);
      if (!row || row <= previousRow) throw invalidWorkbook();
      previousRow = row;
    }
    const cells = new Set<string>();
    for (const match of decoded.matchAll(/<c\b([^>]*)>/g)) {
      const reference = match[1].match(/\br\s*=\s*["']([A-Z]+[1-9]\d*)["']/)?.[1];
      if (!reference || cells.has(reference)) throw invalidWorkbook();
      cells.add(reference);
    }
  }
}

/** Decompress serially and measure emitted bytes; ZIP size metadata is untrusted. */
async function preflight(bytes: Buffer): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    let zip: ZipFile | undefined;
    let activeStream: Readable | undefined;
    let settled = false;
    let expandedBytes = 0;
    let entryCount = 0;
    const names = new Set<string>();
    const finish = (error?: Error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      activeStream?.destroy();
      zip?.close();
      if (error) reject(error); else resolve();
    };
    const timer = setTimeout(() => finish(invalidWorkbook()), PREFLIGHT_TIMEOUT_MS);
    fromBuffer(bytes, { lazyEntries: true, autoClose: false, strictFileNames: true, validateEntrySizes: true }, (error, archive) => {
      if (error || settled) {
        archive?.close();
        finish(invalidWorkbook());
        return;
      }
      zip = archive;
      zip.on("error", () => finish(invalidWorkbook()));
      zip.on("end", () => {
        if (!names.has("[content_types].xml") || !names.has("xl/workbook.xml") || !names.has("_rels/.rels")) {
          finish(invalidWorkbook());
        } else finish();
      });
      zip.on("entry", (entry: Entry) => {
        if (settled) return;
        const path = entry.fileName;
        const name = path.toLowerCase();
        entryCount += 1;
        if (entryCount > MAX_ENTRIES || names.has(name) || path.length > 200
          || /[\\\u0000-\u001f%:]/.test(path) || path.startsWith("/")
          || path.split("/").some((part) => part === "." || part === "..")
          || (entry.generalPurposeBitFlag & 1) !== 0
          || ![0, 8].includes(entry.compressionMethod)
          || entry.uncompressedSize > MAX_ENTRY_BYTES
          || /vbaproject|macros?|externallinks|embeddings|activex|customui/i.test(path)) {
          finish(invalidWorkbook());
          return;
        }
        names.add(name);
        if (path.endsWith("/")) {
          if (entry.uncompressedSize !== 0) finish(invalidWorkbook()); else zip!.readEntry();
          return;
        }
        // Accept only XML parts; embedded binaries/media have no staff-import purpose.
        if (!/\.(?:xml|rels)$/i.test(path)) {
          finish(invalidWorkbook());
          return;
        }
        zip!.openReadStream(entry, (streamError, stream) => {
          if (streamError || settled) {
            stream?.destroy();
            finish(invalidWorkbook());
            return;
          }
          activeStream = stream;
          const chunks: Buffer[] = [];
          let entryBytes = 0;
          stream.on("error", () => finish(invalidWorkbook()));
          stream.on("data", (chunk: Buffer) => {
            entryBytes += chunk.length;
            expandedBytes += chunk.length;
            if (entryBytes > MAX_ENTRY_BYTES || expandedBytes > MAX_EXPANDED_BYTES) finish(invalidWorkbook());
            else chunks.push(chunk);
          });
          stream.on("end", () => {
            if (settled) return;
            activeStream = undefined;
            try {
              inspectXml(name, Buffer.concat(chunks, entryBytes));
              zip!.readEntry();
            } catch {
              finish(invalidWorkbook());
            }
          });
        });
      });
      zip.readEntry();
    });
  });
}

export async function createStaffImportTemplate(): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const staff = workbook.addWorksheet("Staff");
  staff.columns = HEADERS.map((header) => ({ header, key: header, width: header === "email" ? 40 : 28 }));
  staff.getRow(1).font = { bold: true };
  staff.views = [{ state: "frozen", ySplit: 1 }];
  staff.addRows([
    ["Fictional Example Admin", "example.admin@example.invalid", "ADMIN", ""],
    ["Fictional Example Manager", "example.manager@example.invalid", "MANAGER", ""],
    ["Fictional Example Technician", "example.tech@example.invalid", "TECHNICIAN", "EXAMPLE_BRANCH"],
  ]);
  const instructions = workbook.addWorksheet("Instructions");
  instructions.getColumn(1).width = 110;
  instructions.addRows([
    ["Staff import — create new accounts only"],
    ["Replace or remove every fictional example row before uploading. Example emails do not belong to real people."],
    ["Keep Staff column headers exactly: name, email, role, branchCode. Use plain text cells, not formulas."],
    ["Roles: ADMIN, MANAGER, TECHNICIAN. Only TECHNICIAN needs an existing branch code in the selected workspace."],
    ["For ADMIN and MANAGER leave branchCode blank. Do not add passwords, account IDs, or other columns."],
    ["Maximum 100 employees and 1 MiB .xlsx file. Each email must appear once. Existing accounts cannot be changed."],
    ["Preview is validation only. Review the rows and explicitly confirm to create accounts. Temporary passwords are generated by the server."],
  ]);
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

export async function parseStaffImportWorkbook(bytes: Uint8Array): Promise<StaffImportPreview> {
  if (bytes.byteLength === 0 || bytes.byteLength > STAFF_IMPORT_MAX_BYTES) {
    throw new Error("Upload a nonempty .xlsx file no larger than 1 MiB.");
  }
  const buffer = Buffer.from(bytes);
  if (buffer.byteLength < 4 || buffer.readUInt32LE(0) !== 0x04034b50) throw invalidWorkbook();
  await preflight(buffer);
  const workbook = new ExcelJS.Workbook();
  try {
    // XML bytes and physical coordinates have already been bounded. Ignore
    // presentation/unsupported nodes to avoid expensive reconciliation work.
    const loadOptions = { maxRows: MAX_PHYSICAL_ROW, maxCols: MAX_PHYSICAL_COLUMN, ignoreNodes: [
      "sheetPr", "dimension", "sheetViews", "sheetFormatPr", "cols", "autoFilter",
      "dataValidations", "conditionalFormatting", "pageMargins", "pageSetup",
      "headerFooter", "printOptions", "sheetProtection", "extLst",
    ] };
    // ExcelJS 4.4 declares its input as ArrayBuffer; JSZip accepts an exact
    // ArrayBuffer as well as Node Buffer. Copy the view to avoid extra bytes
    // from Buffer's pooled backing allocation and avoid a type assertion.
    await workbook.xlsx.load(Uint8Array.from(buffer).buffer, loadOptions);
  } catch {
    throw invalidWorkbook();
  }
  const sheet = workbook.getWorksheet("Staff");
  if (!sheet || sheet.state !== "visible" || workbook.worksheets.some((item) => !["Staff", "Instructions"].includes(item.name))) {
    throw new Error("The workbook must contain a visible Staff sheet and only an optional Instructions sheet.");
  }
  if (sheet.columnCount > HEADERS.length || HEADERS.some((header, index) => sheet.getCell(1, index + 1).value !== header)) {
    throw new Error("Keep exactly these Staff headers in order: name, email, role, branchCode. Passwords and extra columns are not accepted.");
  }
  const rows: StaffImportRow[] = [];
  const emailRows = new Map<string, number[]>();
  // eachRow skips empty/formatting-only rows, including trailing template rows.
  sheet.eachRow((row, rowNumber) => {
    if (rowNumber === 1) return;
    const values = HEADERS.map((_, index) => row.getCell(index + 1).value);
    if (values.every((value) => value === null || (typeof value === "string" && value.trim() === ""))) return;
    if (rows.length >= STAFF_IMPORT_MAX_ROWS) throw new Error("Import at most 100 employees at a time.");
    const errors: string[] = [];
    const text = values.map((value, index) => {
      if (value === null) return "";
      if (typeof value !== "string") {
        errors.push(`${HEADERS[index]} must be plain text; formulas and nontext cells are not accepted.`);
        return "";
      }
      return value.trim();
    });
    const normalizedEmail = text[1].toLowerCase();
    if (normalizedEmail) emailRows.set(normalizedEmail, [...(emailRows.get(normalizedEmail) ?? []), rows.length]);
    const result = staffAccountInputSchema.safeParse({ name: text[0], email: text[1], role: text[2], branchCode: text[3] || null });
    if (!result.success) {
      errors.push(...result.error.issues.map((issue) => `${issue.path.join(".")}: ${
        issue.code === "invalid_enum_value" ? "Use ADMIN, MANAGER or TECHNICIAN." : issue.message
      }`));
    }
    rows.push({ row: rowNumber, input: result.success && errors.length === 0 ? result.data : null, errors });
  });
  if (rows.length === 0) throw new Error("Add at least one employee to the Staff sheet.");
  for (const indices of emailRows.values()) {
    if (indices.length < 2) continue;
    for (const index of indices) {
      rows[index] = { ...rows[index], input: null, errors: [...rows[index].errors, "Email is duplicated in this workbook."] };
    }
  }
  const validCount = rows.filter((row) => row.input !== null).length;
  return { rows, validCount, invalidCount: rows.length - validCount };
}
